#!/usr/bin/env python
import os
import sys
import subprocess

def build_dead_msg(class_name):
    return f"[class=\"{class_name}\"] move scratchpad"

def build_head_msg(head):
    return (f"[class=\"{head}\"] scratchpad show, "
             "resize set 1100 780, move position center")

def show_and_hide_rest(classes):
    head, *tail = classes
    for name in tail:
        subprocess.run(["i3-msg", build_dead_msg(name)])
    subprocess.run(["i3-msg", build_head_msg(head)])

def show_head_class(head_class):
    subprocess.run(["i3-msg", build_head_msg(head_class)])

def rotate(xs, direction):
    return xs[int(direction):] + xs[:int(direction)]

def seek_and_overwrite(file, content):
    file.seek(0)
    file.write(content)
    file.truncate()

def compile_to_contents(xs):
    return "\n".join(xs)

def usage():
    print("USAGE")
    print("Here how you do:")

def assert_file_exists(file_path):
    if not os.path.exists(file_path):
      print(f"ERROR: class store at {file_path} no existy, friendo")
      usage()
      sys.exit(1)

def main():
    rotate_direction = None
    if len(sys.argv) > 1:
      rotate_direction = sys.argv[1]
    script_path = os.path.abspath(__file__)
    script_dir  = os.path.dirname(script_path)
    store_name  = "class.store"
    store_path  = os.path.join(script_dir, store_name)
    assert_file_exists(store_path)
    try:
        with open(store_path, "r+") as f:
            win_classes = [line.rstrip() for line in f]
            if rotate_direction:
                win_classes = rotate(win_classes, rotate_direction)
                f_content = compile_to_contents(win_classes)
                seek_and_overwrite(f, f_content)
                show_and_hide_rest(win_classes)
                sys.exit(0)
            show_head_class(win_classes[0])
    except Exception as e:
        print(f"ERROR: stuff gone wrong because of:\n${str(e)}")
        sys.exit(1)

if __name__ == "__main__":
    main()
